import { AllConfigs } from '@/types/config';

// Valeurs par défaut pour les configurations
export const defaultConfigs: AllConfigs = {
  general: {
    siteName: 'Larian',
    siteDescription: 'Site officiel de Larian - Musique électronique et événements.',
    contactEmail: 'contact@djlarian.com',
    timeZone: 'Europe/Paris',
    dateFormat: 'DD/MM/YYYY',
  },
  appearance: {
    primaryColor: '#8B5CF6',
    secondaryColor: '#3B82F6',
    darkMode: true,
    animationsEnabled: true,
    logoUrl: '/images/logo.png',
    faviconUrl: '/favicon.ico',
  },
  homepage: {
    heroTitle: 'LARIAN',
    heroSubtitle: 'Electronic Music Producer & Innovative Performer',
    heroExploreButtonText: 'Explore Music',
    heroExploreButtonUrl: '/music',
    heroEventsButtonText: 'Upcoming Events',
    heroEventsButtonUrl: '/events',
    heroBackgroundVideo: '/videos/hero-background.mp4',
    heroPosterImage: '/images/hero-poster.jpg',
    sectionsOrder: 'hero,releases,visualizer,events,stream',
    releasesEnabled: true,
    releasesTitle: 'Latest Releases',
    releasesCount: 3,
    visualizerEnabled: true,
    visualizerTitle: 'Experience the Sound',
    eventsEnabled: true,
    eventsTitle: 'Upcoming Events',
    eventsCount: 3,
    eventsViewAllText: 'View All Events',
    eventsViewAllUrl: '/events',
    streamEnabled: true,
    streamTitle: 'Live Stream',
    streamSubtitle: 'Join the Live Experience',
    streamDescription:
      'Tune in to my live streams where I share my creative process, perform exclusive sets, and interact with the community in real-time.',
    twitchUsername: 'larianmusic',
    twitchFollowButtonText: 'Follow on Twitch',
    twitchFollowButtonUrl: 'https://twitch.tv/larianmusic',
    streamNotifyButtonText: 'Get Notified',
    streamStatsEnabled: true,
    streamFollowers: '24K+',
    streamHoursStreamed: '150+',
    streamTracksPlayed: '500+',
  },
  notifications: {
    emailNotifications: true,
    adminAlerts: true,
    newUserNotifications: true,
    eventReminders: true,
    marketingEmails: false,
  },
  security: {
    twoFactorAuth: false,
    passwordExpiration: 90,
    ipRestriction: false,
    failedLoginLimit: 5,
    sessionTimeout: 60,
  },
  api: {
    apiEnabled: true,
    rateLimit: 100,
    webhookUrl: '', // À configurer dans /admin/configuration si nécessaire
    umamiEnabled: true,
    umamiSiteId: '484ec662-e403-4498-a654-ca04b9b504c3', // ID du site Umami (local development)
  },
};
