import { auth } from '@/auth';
import prisma from '@/lib/prisma';
import { NextResponse } from 'next/server';

async function handleDownloadRequest(req: Request) {
  try {
    const { searchParams } = new URL(req.url);

    let licenseId = searchParams.get('id');
    let email = searchParams.get('email');
    let licenseKey = searchParams.get('licenseKey');
    let os = searchParams.get('os'); // 'mac' or 'windows'

    if (req.method === 'POST') {
      try {
        const body = await req.json();
        if (body.id) licenseId = body.id;
        if (body.email) email = body.email;
        if (body.licenseKey) licenseKey = body.licenseKey;
        if (body.os) os = body.os;
      } catch (e) {
        // Ignore JSON parse errors
      }
    }

    if (!os) {
      return new NextResponse('Missing os parameter', { status: 400 });
    }

    let license;

    // 1. Verify license
    if (email && licenseKey) {
      // Auth via email + licenseKey (Desktop App flow)
      license = await prisma.license.findUnique({
        where: {
          licenseKey: licenseKey,
        },
        include: {
          user: true,
        },
      });

      if (!license || license.user.email?.toLowerCase() !== email.toLowerCase()) {
        return new NextResponse('Invalid email or license key', { status: 401 });
      }
    } else if (licenseId) {
      // Auth via session + licenseId (Web UI flow)
      const session = await auth();
      if (!session?.user) {
        return new NextResponse('Unauthorized', { status: 401 });
      }

      license = await prisma.license.findUnique({
        where: {
          id: licenseId,
          userId: session.user.id, // Ensure owner
        },
      });

      if (!license) {
        return new NextResponse('License not found', { status: 404 });
      }
    } else {
      return new NextResponse('Missing authentication parameters', { status: 400 });
    }

    if (license.revoked) {
      return new NextResponse('License revoked', { status: 403 });
    }

    // 2. GitHub Integration
    const repo = process.env.GITHUB_PLUGIN_REPO || 'Jujulu67/LarianCrusher';
    const token = process.env.GITHUB_TOKEN;

    if (!token) {
      console.error('GITHUB_TOKEN not configured');
      return new NextResponse('Server configuration error', { status: 500 });
    }

    // Fetch latest release info from GitHub
    const releaseRes = await fetch(`https://api.github.com/repos/${repo}/releases/latest`, {
      headers: {
        Authorization: `token ${token}`,
        Accept: 'application/vnd.github.v3+json',
      },
      cache: 'no-store', // Disable cache to ensure we get the latest assets
    });

    if (!releaseRes.ok) {
      console.error('Failed to fetch latest release:', await releaseRes.text());
      return new NextResponse('Failed to fetch installers', { status: 502 });
    }

    const release = await releaseRes.json();

    // Find asset based on OS
    // Expecting filenames like: LarianCrusher-Mac.pkg, LarianCrusher-Win.exe, etc.
    const asset = release.assets.find((a: any) => {
      const name = a.name.toLowerCase();
      if (os === 'mac') {
        return name.endsWith('.pkg') || name.endsWith('.dmg') || name.includes('mac');
      }
      if (os === 'windows') {
        return name.endsWith('.exe') || name.endsWith('.msi') || name.includes('win');
      }
      return false;
    });

    if (!asset) {
      return new NextResponse(`No installer found for ${os}`, { status: 404 });
    }

    // 3. Get the asset from GitHub
    // We use manual redirect handling to ensure the Authorization header
    // is NOT sent to the redirect destination (S3/Azure), which often causes 403s.
    // This allows us to capture the temporary signed URL generated by GitHub's Release API.
    const assetRes = await fetch(asset.url, {
      headers: {
        Authorization: `token ${token}`,
        Accept: 'application/octet-stream',
      },
      redirect: 'manual',
    });

    let downloadUrl: string | null = null;

    if (assetRes.status === 302) {
      downloadUrl = assetRes.headers.get('location');
    }

    if (!downloadUrl) {
      console.error(
        `Failed to get redirect URL from GitHub: ${assetRes.status} ${assetRes.statusText}`
      );
      return new NextResponse(`Failed to resolve installer URL from GitHub`, { status: 502 });
    }

    // If it's a POST request (specifically from the Desktop plugin),
    // it's cleaner and safer to just return the signed URL and let the native plugin download it,
    // saving Vercel execution bandwidth.
    if (req.method === 'POST') {
      return NextResponse.json(
        { downloadUrl },
        {
          headers: {
            'Cache-Control': 'no-store',
          },
        }
      );
    }

    // For GET request (Web UI), proxy the stream safely
    const finalAssetRes = await fetch(downloadUrl); // Don't send Authorization to the redirect URL

    if (!finalAssetRes.ok) {
      console.error(
        `Failed to download asset: ${finalAssetRes.status} ${finalAssetRes.statusText}`,
        {
          url: downloadUrl,
          assetName: asset.name,
        }
      );
      return new NextResponse(`Failed to proxy asset from GitHub (${finalAssetRes.status})`, {
        status: 502,
      });
    }

    // Return the stream with correct headers
    return new NextResponse(finalAssetRes.body, {
      headers: {
        'Content-Type': asset.content_type || 'application/octet-stream',
        'Content-Disposition': `attachment; filename="${asset.name}"`,
        'Content-Length': asset.size.toString(),
        'Cache-Control': 'no-store',
      },
    });
  } catch (error) {
    console.error('[DOWNLOAD_ERROR]', error);
    return new NextResponse('Internal error', { status: 500 });
  }
}

export async function GET(req: Request) {
  return handleDownloadRequest(req);
}

export async function POST(req: Request) {
  return handleDownloadRequest(req);
}
